namespace FinanceManager.Bot.Enums;
public enum WorkflowState
{
    Default,
    CreateMenu,
    SelectMenu,
    AddAccount,
    CreateAccountStart,
    ChooseAccountName,
    SendCurrencies,
    ChooseCurrency,
    SendInputAccountInitialBalance,
    SetAccountInitialBalance,
    CreateAccountEnd,

    DeleteAccount,
    AddExpense,
    DeleteExpense,
    AddIncome,
    DeleteIncome,
    
    SendInputTransactionDate,
    SetTransactionDate,
    SendInputTransactionAmount,
    SetTransactionAmount,
    SendTransactionCategories,
    ChooseTransactionCategory,
    RegisterTransaction,

    CreateSettingsMenu,
    SelectSettingsMenu,
    ManageCategories,
    ManageTransactions,
    ManageAccounts,

    SendChooseNewCategoryType,
    SetNewCategoryType,
    SendInputNewCategoryName,
    SetNewCategoryName,
    SendInputNewCategoryEmoji,
    SetNewCategoryEmoji,
    RegisterNewCategory,

    SendChooseDeletingCategoryType,
    SetDeletingCategoryType,
    SendChooseCategoryToDelete,
    ChooseCategoryToDelete,
    SendSwitchTransactionsToAnotherCategory,
    HandleSwitchTransactionsToAnotherCategory,
    SendChooseCategoriesToSwitchTransactions,
    ChooseCategoryToSwitch,

    SendChooseRenamingCategoryType,
    SetRenamingCategoryType,
    SendChooseRenamingCategory,
    ChooseCategoryToRename,
    SendInputCategoryName,
    SetCategoryName,
    SendInputCategoryEmoji,
    SetCategoryEmoji,
    RegisterRenameCategory,

    AddTransfer,
    DeleteTransfer,
    History,
}
